spring:
  application:
    name: humanResources

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jakarta:
        persistance:
          sharedCache:
            mode: UNSPECIFIED

  datasource:
    url: jdbc:mysql://localhost:3306/humanResources
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver